services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /userbot-application
    volumes:
      - ./userbot-application:/userbot-application
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    image: node:18
    working_dir: /userbot-application-ui
    volumes:
      - ./userbot-application-ui:/userbot-application-ui
    command: >
      sh -c "npm install &&
             npm run build &&
             npm start"
    ports:
      - "3000:3000"
